version = 0.1

[default]
[default.global.parameters]
stack_name = "rtdbc-backend"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
parameter_overrides = [
    "Environment=production",
    "BusinessEmail=contact@rtdynamicbc.co.za",
    "FromEmail=noreply@rtdynamicbc.co.za",
    "SendConfirmation=true"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development environment configuration
[development]
[development.global.parameters]
stack_name = "rtdbc-backend-dev"

[development.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
parameter_overrides = [
    "Environment=development",
    "BusinessEmail=contact@rtdynamicbc.co.za",
    "FromEmail=noreply@rtdynamicbc.co.za",
    "SendConfirmation=true"
]

# Staging environment configuration
[staging]
[staging.global.parameters]
stack_name = "rtdbc-backend-staging"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
parameter_overrides = [
    "Environment=staging",
    "BusinessEmail=contact@rtdynamicbc.co.za",
    "FromEmail=noreply@rtdynamicbc.co.za",
    "SendConfirmation=true"
]